# Generated by Django 6.0.4 on 2026-04-12 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_region_model'),
        ('organizations', '0003_assign_west_midlands_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(help_text='Displayed on event cards and list views', max_length=300, verbose_name='short description')),
                ('location_name', models.CharField(blank=True, default='', max_length=255, verbose_name='location name')),
                ('location_address', models.TextField(blank=True, default='', verbose_name='location address')),
                ('is_online', models.BooleanField(default=False, verbose_name='online event')),
                ('online_url', models.URLField(blank=True, default='', verbose_name='online URL')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('image', models.ImageField(blank=True, upload_to='events/images/', verbose_name='image')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='capacity')),
                ('booking_url', models.URLField(blank=True, default='', verbose_name='booking URL')),
                ('is_free', models.BooleanField(default=True, verbose_name='free event')),
                ('cost_description', models.CharField(blank=True, default='', help_text='e.g. "£5 suggested donation"', max_length=100, verbose_name='cost description')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='source URL')),
                ('is_scraped', models.BooleanField(default=False, verbose_name='scraped')),
                ('areas', models.ManyToManyField(blank=True, help_text='Geographic areas this event is relevant to', to='core.geographicarea', verbose_name='areas')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization', verbose_name='organisation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.region', verbose_name='region')),
                ('support_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.supportstream', verbose_name='support stream')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start', models.DateTimeField(db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='cancelled')),
                ('override_title', models.CharField(blank=True, default='', max_length=255, verbose_name='override title')),
                ('override_description', models.TextField(blank=True, default='', verbose_name='override description')),
                ('override_location_name', models.CharField(blank=True, default='', max_length=255, verbose_name='override location name')),
                ('override_location_address', models.TextField(blank=True, default='', verbose_name='override location address')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'Event Occurrence',
                'verbose_name_plural': 'Event Occurrences',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='EventRecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rrule', models.TextField(help_text='RFC 5545 recurrence rule, e.g. FREQ=WEEKLY;BYDAY=MO or FREQ=MONTHLY;BYMONTHDAY=1', verbose_name='rrule')),
                ('dtstart', models.DateTimeField(verbose_name='first occurrence start')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Applied to every generated occurrence', verbose_name='duration (minutes)')),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='repeat until')),
                ('count', models.PositiveIntegerField(blank=True, help_text='Leave blank for indefinite recurrence', null=True, verbose_name='max occurrences')),
                ('exceptions', models.JSONField(blank=True, default=list, help_text='List of ISO-8601 datetimes excluded from the recurrence', verbose_name='exception dates')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'Recurrence Rule',
                'verbose_name_plural': 'Recurrence Rules',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['region', 'is_published', 'start'], name='events_even_region__2b7c52_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'is_published'], name='events_even_organiz_7bd47f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['event', 'start'], name='events_even_event_i_c585a0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['start', 'end', 'is_cancelled'], name='events_even_start_111956_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.UniqueConstraint(fields=('event', 'start'), name='unique_event_occurrence'),
        ),
    ]
