# Generated by Django 6.0.4 on 2026-04-12 08:36

import apps.referrals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_orgonboardingstate_organization_crm_webhook_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference_number', models.CharField(default=apps.referrals.models._referral_ref, help_text='Human-readable reference, e.g. WM-2026-123456', max_length=30, unique=True, verbose_name='reference number')),
                ('form_data', models.JSONField(default=dict, help_text='Non-PII fields: priority, service_needed, urgency_reason, etc.', verbose_name='form data')),
                ('encrypted_pii', models.TextField(blank=True, default='', help_text='Fernet-encrypted JSON of all PII fields', verbose_name='encrypted PII')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=10, verbose_name='priority')),
                ('consent_given', models.BooleanField(default=False, verbose_name='consent given')),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='consent timestamp')),
                ('consent_statement', models.TextField(blank=True, default='', help_text='The exact consent text the client agreed to', verbose_name='consent statement')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('escalated', models.BooleanField(default=False, help_text='Set True when unacknowledged after 48h', verbose_name='escalated')),
                ('notes', models.TextField(blank=True, default='', verbose_name='internal notes')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='organizations.organization', verbose_name='organisation')),
                ('referring_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to='organizations.organization', verbose_name='referring organisation')),
                ('referring_user', models.ForeignKey(blank=True, help_text='Null for anonymous self-referrals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='referring user')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('channel', models.CharField(choices=[('in_platform', 'In-platform inbox'), ('email', 'Email'), ('csv', 'CSV download'), ('print', 'Print / paper'), ('crm_webhook', 'CRM webhook')], max_length=20, verbose_name='channel')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='queued', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempted at')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='error log')),
                ('last_response_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='last HTTP response')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='referrals.referral', verbose_name='referral')),
            ],
            options={
                'verbose_name': 'Referral Delivery',
                'verbose_name_plural': 'Referral Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('email', 'Email address'), ('phone', 'Phone number'), ('url', 'URL / link'), ('date', 'Date'), ('dob', 'Date of birth'), ('number', 'Number'), ('nhs_number', 'NHS number'), ('ni_number', 'National Insurance number'), ('passport_number', 'Passport number'), ('dbs_reference', 'DBS reference number'), ('id_number', 'Other ID number'), ('postcode', 'Postcode'), ('address', 'Full address'), ('select', 'Dropdown (single choice)'), ('radio', 'Radio buttons'), ('checkbox', 'Checkboxes (multi-select)'), ('boolean', 'Yes / No'), ('file', 'File upload'), ('consent', 'GDPR consent statement')], max_length=30, verbose_name='field type')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('help_text', models.CharField(blank=True, default='', max_length=300, verbose_name='help text')),
                ('placeholder', models.CharField(blank=True, default='', max_length=200, verbose_name='placeholder')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('options', models.JSONField(blank=True, default=list, help_text='For select/radio/checkbox fields: list of option strings', verbose_name='options')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_form_fields', to='organizations.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'Referral Form Field',
                'verbose_name_plural': 'Referral Form Fields',
                'ordering': ['organization', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='from')),
                ('to_status', models.CharField(max_length=20, verbose_name='to')),
                ('note', models.TextField(blank=True, default='', verbose_name='note')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='changed at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='referrals.referral', verbose_name='referral')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='referrals_r_organiz_61f78c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referring_user'], name='referrals_r_referri_253fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['acknowledged_at', 'escalated'], name='referrals_r_acknowl_a2a023_idx'),
        ),
        migrations.AddConstraint(
            model_name='referraldelivery',
            constraint=models.UniqueConstraint(fields=('referral', 'channel'), name='unique_referral_channel'),
        ),
    ]
