# Generated by Django 6.0.4 on 2026-04-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationservice_category_and_more'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referralformfield',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='unique_referral_form_field_label_per_org'),
        ),
    ]
