# Generated by Django 6.0.4 on 2026-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='home latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_location_label',
            field=models.CharField(blank=True, default='', help_text='Town or district from postcode lookup (read-only cache).', max_length=200, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='home longitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_postcode',
            field=models.CharField(blank=True, default='', help_text='Used to show organisations and events near you (about 20 miles).', max_length=20, verbose_name='home postcode'),
        ),
    ]
