# Generated by Django 6.0.4 on 2026-04-12 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_region_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icon', models.CharField(blank=True, default='', help_text='CSS/emoji icon identifier for UI display', max_length=50, verbose_name='icon')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory', verbose_name='parent category')),
                ('region', models.ForeignKey(blank=True, help_text='Leave blank for platform-wide categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='core.region', verbose_name='region')),
                ('support_stream', models.ForeignKey(blank=True, help_text='Optional link to the legacy flat stream', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.supportstream', verbose_name='support stream')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
