# Generated by Django 6.0.4 on 2026-04-12 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('logo', models.ImageField(blank=True, upload_to='regions/logos/', verbose_name='logo')),
                ('brand_color_primary', models.CharField(default='#2563eb', help_text='Hex code e.g. #2563eb', max_length=7, verbose_name='primary colour')),
                ('brand_color_accent', models.CharField(default='#16a34a', help_text='Hex code e.g. #16a34a', max_length=7, verbose_name='accent colour')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='contact email')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
                ('lat_center', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude centre')),
                ('lng_center', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude centre')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
    ]
