# Generated by Django 6.0.4 on 2026-04-13 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_region_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('source_link', models.URLField(help_text='Link to the Flickr photo page for attribution.', max_length=512, unique=True, verbose_name='photo page URL')),
                ('image_url', models.URLField(max_length=512, verbose_name='image URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('attribution', models.CharField(blank=True, default='', max_length=255, verbose_name='attribution')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Community photo',
                'verbose_name_plural': 'Community photos',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
