# Generated by Django 6.0.4 on 2026-04-13 18:04

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_community_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('placement', models.CharField(choices=[('home_hero', 'Home hero (full-bleed stack)'), ('pathways_banner', 'Pathways banner (future)')], db_index=True, default='home_hero', max_length=32, verbose_name='placement')),
                ('image', models.ImageField(upload_to=apps.core.models.site_image_upload_to, verbose_name='image')),
                ('alt_text', models.CharField(help_text='Short description for screen readers (required for accessibility).', max_length=255, verbose_name='alternative text')),
                ('caption', models.TextField(blank=True, default='', verbose_name='caption')),
                ('credit', models.CharField(blank=True, default='', help_text='e.g. Photographer name or licence line, shown on the public site.', max_length=255, verbose_name='credit / attribution')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_images_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'Site image',
                'verbose_name_plural': 'Site images',
                'ordering': ['placement', 'display_order', 'created_at'],
            },
        ),
    ]
