# Generated by Django 6.0.4 on 2026-04-16 07:47

import apps.assistant.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organizationservice_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),   # CREATE EXTENSION IF NOT EXISTS vector — MUST be first
        migrations.CreateModel(
            name='AssistantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='session key')),
                ('query_text', models.TextField(max_length=500, verbose_name='query text')),
                ('response_text', models.TextField(blank=True, default='', verbose_name='response text')),
                ('sources', models.JSONField(blank=True, null=True, verbose_name='sources')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='response time (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Assistant Query',
                'verbose_name_plural': 'Assistant Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='session key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='last active')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('sources', models.JSONField(blank=True, help_text='List of {"name": "...", "url": "..."} dicts', null=True, verbose_name='sources')),
                ('crisis_detected', models.BooleanField(default=False, verbose_name='crisis detected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to=apps.assistant.models.org_doc_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='file')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='indexed at')),
                ('index_error', models.TextField(blank=True, default='', verbose_name='index error')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization', verbose_name='organisation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'Org Document',
                'verbose_name_plural': 'Org Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
