# Generated by Django 6.0.4 on 2026-04-13 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_region_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='Plain-language introduction shown on the pathway card and hero.', verbose_name='description')),
                ('icon_name', models.CharField(default='user-group', help_text="Heroicons outline icon name, e.g. 'user-group', 'home', 'shield-check'.", max_length=60, verbose_name='icon name')),
                ('audience_tag', models.CharField(choices=[('prison_leavers', 'Prison Leavers'), ('homeless', 'Homelessness'), ('both', 'Both')], default='both', max_length=20, verbose_name='audience')),
                ('meta_description', models.CharField(blank=True, default='', help_text='SEO meta description (max 160 chars).', max_length=160, verbose_name='meta description')),
                ('is_published', models.BooleanField(default=False, help_text='Only published pathways appear on the public site.', verbose_name='published')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='core.region', verbose_name='region')),
            ],
            options={
                'verbose_name': 'Pathway',
                'verbose_name_plural': 'Pathways',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PathwaySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, default='', help_text='Introductory text for this section. Plain text.', verbose_name='body')),
                ('icon_name', models.CharField(default='information-circle', help_text='Heroicons outline icon name for this section.', max_length=60, verbose_name='icon name')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pathways.pathway', verbose_name='pathway')),
            ],
            options={
                'verbose_name': 'Pathway Section',
                'verbose_name_plural': 'Pathway Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PathwayGuideItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, default='', help_text='Additional detail or explanation. Plain text.', verbose_name='body')),
                ('link_url', models.URLField(blank=True, default='', help_text='Optional — links to an org profile, external resource, or gov page.', verbose_name='link URL')),
                ('link_label', models.CharField(blank=True, default='', help_text="Button label for the link, e.g. 'Find your nearest centre'.", max_length=100, verbose_name='link label')),
                ('is_urgent', models.BooleanField(default=False, help_text='Highlight this item in amber — use for time-critical or emergency steps.', verbose_name='urgent')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_items', to='pathways.pathwaysection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'Guide Item',
                'verbose_name_plural': 'Guide Items',
                'ordering': ['display_order'],
            },
        ),
    ]
