# Generated by Django 6.0.4 on 2026-04-12 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, default='', help_text='Snapshot at time of action in case user is later deleted', max_length=254, verbose_name='actor email')),
                ('action', models.CharField(choices=[('referral_created', 'Referral created'), ('referral_status_changed', 'Referral status changed'), ('referral_pii_accessed', 'Referral PII accessed'), ('referral_deleted', 'Referral deleted'), ('delivery_queued', 'Delivery queued'), ('delivery_sent', 'Delivery sent'), ('delivery_failed', 'Delivery failed'), ('delivery_acknowledged', 'Delivery acknowledged'), ('org_created', 'Organisation created'), ('org_updated', 'Organisation updated'), ('onboarding_step_completed', 'Onboarding step completed'), ('onboarding_completed', 'Onboarding completed'), ('user_login', 'User login'), ('user_approved', 'User approved'), ('user_role_changed', 'User role changed'), ('admin_action', 'Admin action')], max_length=40, verbose_name='action')),
                ('object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='target ID')),
                ('delta', models.JSONField(blank=True, default=dict, help_text='Dict of changed fields: {field: [old, new]}', verbose_name='delta')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: IP address, channel, etc.', verbose_name='metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('prev_hash', models.CharField(blank=True, default='', help_text='SHA-256 of the previous AuditEntry, or empty for first entry', max_length=64, verbose_name='previous hash')),
                ('entry_hash', models.CharField(help_text='SHA-256 of (prev_hash + action + object_id + timestamp_iso)', max_length=64, verbose_name='entry hash')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='target type')),
            ],
            options={
                'verbose_name': 'Audit Entry',
                'verbose_name_plural': 'Audit Entries',
                'ordering': ['timestamp'],
            },
        ),
    ]
