# Generated by Django 6.0.4 on 2026-04-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditentry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='entry_hash',
            field=models.CharField(help_text='SHA-256 of (prev_hash + action + object_id + timestamp_iso)', max_length=64, unique=True, verbose_name='entry hash'),
        ),
    ]
