# Generated by Django 6.0.4 on 2026-04-11 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='Full description of the organization', verbose_name='description')),
                ('short_description', models.CharField(help_text='For card/list views', max_length=300, verbose_name='short description')),
                ('translated_descriptions', models.JSONField(blank=True, default=dict, help_text='Optional translations: {"pl": "...", "pa": "...", ...}', verbose_name='translated descriptions')),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/', verbose_name='logo')),
                ('hero_image', models.ImageField(blank=True, upload_to='organizations/heroes/', verbose_name='hero image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='status')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(default='Wolverhampton', max_length=100, verbose_name='city')),
                ('postcode', models.CharField(blank=True, default='', max_length=10, verbose_name='postcode')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('accepts_referrals', models.BooleanField(default=True, verbose_name='accepts referrals')),
                ('accepts_self_referrals', models.BooleanField(default=True, verbose_name='accepts self-referrals')),
                ('referral_email', models.EmailField(blank=True, default='', help_text='Email to notify when a referral is received', max_length=254, verbose_name='referral email')),
                ('referral_instructions', models.TextField(blank=True, default='', help_text='Special instructions for making referrals to this org', verbose_name='referral instructions')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='e.g. {"monday": {"open": "09:00", "close": "17:00"}, ...}', verbose_name='opening hours')),
                ('events_page_url', models.URLField(blank=True, default='', help_text='URL to scrape for events weekly', verbose_name='events page URL')),
                ('news_page_url', models.URLField(blank=True, default='', help_text='URL to scrape for news weekly', verbose_name='news page URL')),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='last indexed')),
                ('areas_served', models.ManyToManyField(blank=True, to='core.geographicarea', verbose_name='areas served')),
                ('support_streams', models.ManyToManyField(blank=True, help_text='Which support streams does this organization serve?', related_name='organizations', to='core.supportstream', verbose_name='support streams')),
                ('tags', models.ManyToManyField(blank=True, related_name='organizations', to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('access_model', models.CharField(choices=[('drop_in', 'Drop-in'), ('self_referral', 'Self-referral'), ('professional_referral', 'Professional Referral Required'), ('gp_referral', 'GP Referral Required'), ('assessment', 'Assessment Required')], default='self_referral', max_length=30, verbose_name='access model')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='minimum age')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum age')),
                ('eligibility_notes', models.TextField(blank=True, default='', help_text="E.g. 'Must be registered with a Wolverhampton GP'", verbose_name='eligibility notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='organizations.organization', verbose_name='organization')),
                ('support_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supportstream', verbose_name='support stream')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Organization Service',
                'verbose_name_plural': 'Organization Services',
                'ordering': ['name'],
            },
        ),
    ]
