# Generated by Django 6.0.4 on 2026-04-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_region_model'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Geographic deployment region for this organisation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.region', verbose_name='region'),
        ),
    ]
