# Generated by Django 6.0.4 on 2026-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_assign_west_midlands_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_steps', models.JSONField(blank=True, default=list, help_text='List of step keys that have been saved', verbose_name='completed steps')),
                ('is_complete', models.BooleanField(default=False, verbose_name='onboarding complete')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'Org Onboarding State',
                'verbose_name_plural': 'Org Onboarding States',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 secret for signing webhook payloads', max_length=128, verbose_name='CRM webhook secret'),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_webhook_url',
            field=models.URLField(blank=True, default='', help_text='POST target for outbound referral JSON payloads', verbose_name='CRM webhook URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='referral_delivery_channels',
            field=models.JSONField(blank=True, default=list, help_text='Channels the org accepts referrals through: in_platform, email, csv, print, crm_webhook', verbose_name='referral delivery channels'),
        ),
    ]
