# Generated by Django 6.0.4 on 2026-04-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_orgonboardingstate_organization_crm_webhook_secret_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_services', to='services.servicecategory', verbose_name='service category'),
        ),
        migrations.AddField(
            model_name='orgonboardingstate',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='organizations.organization', verbose_name='organisation'),
        ),
    ]
